### ISSUE TITLE
CTJCF1003E Configuration service server error

### ISSUE THREAD

**Issue by exrajat** [fsilveir/ipm-cli#8]
Hello 

We are getting below error in ipm login

You're not authenticated, please proceed with authentication
1  - IPM Account: private-account           Subscription: 10.206.0.101:8091                   region: na

Choose the number of the subscription you want to login, or type the subscription 
(ex. fea2ea0f40c71c59d11c5a49d9269d0e / 9.212.149.105:8091 ):1
Type your IPM username (ex.: fsilveir@br.ibm.com / apmadmin): apmadmin
Type your password: 
ERROR - Failed to perform login. Please confirm you can log directly to your subscription.

HTTP STATUS CODE  500
{"_code":"CTJCF1003E","_message":"CTJCF1003E Configuration service server error.","_description":"There is problem with checking authorization for user: user:customRealm/apmadmin for resourceId: /ui/tasks/thresholdmanager with action: view","_level":"ERROR","_moreInfo":null}

**Comment by fsilveir** [comment]
Hi @exrajat, I've made some updates on the login and login validation functions, please check new release [0.5.0](https://github.com/fsilveir/ipm-cli/releases/tag/v0.5.0), and let me know if you're still experiencing the same issue.

Thx!

**Comment by fsilveir** [comment]
Tested and confirmed directly with @exrajat that the latest release fixed the problem, therefore closing this issue.
